name: Release Pub Package
description: Release a flutter/dart package on Github

runs:
  using: node12
  main: dist/index.js

inputs:
  previous-version:
    description: 'The latest active version released'
    required: false
  
  changelog-file:
    description: 'The path to the changelog file. Defaults to $GITHUB_WORKSPACE/CHANGELOG.md'
    required: false
  
  is-draft:
    description: 'Whether the release is a draft'
    required: false
    default: false
  
  pre-release-command:
    description: 'Commands to run before publishing the release on Github'
    required: false

  post-release-command:
    description: 'Commands to run after publishing the release on Github'
    required: false
